<template>
    <div class="tooltip" v-if="show" :class="classAnimation">
        {{ message }}
    </div>
</template>

<script setup>
import { defineProps, onMounted, ref, watch } from 'vue';
const props = defineProps({
    message: {
        type: String,
        required: true
    },
    show: {
        type: Boolean,
        default: false
    }
})

const classAnimation = ref('')

onMounted(() => {
    if(props.show){
        classAnimation.value ='scale-in-center'
    }
})

watch(() => props.show, (newVal) => {
    if(newVal){
        classAnimation.value ='scale-in-center'
    }
})

</script>
<style scoped>
.tooltip {
    width: fit-content;
    height: fit-content;
    position: absolute;
    z-index: 1000;
    margin-bottom: 55px;
    transition: 1s ease;
    color: var(--text-color);
    font-size: 12px;
    padding: 5px;
    background-color: var(--primary-color-light);
    border-radius: 5px;
    border: 1px solid var(--text-color);
}

.scale-in-center {
    -webkit-animation: scale-in-center 0.5s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
    animation: scale-in-center 0.5s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
}

/* ----------------------------------------------
 * Generated by Animista on 2024-8-20 23:33:30
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation scale-in-center
 * ----------------------------------------
 */
@-webkit-keyframes scale-in-center {
    0% {
        -webkit-transform: scale(0);
        transform: scale(0);
        opacity: 1;
    }

    100% {
        -webkit-transform: scale(1);
        transform: scale(1);
        opacity: 1;
    }
}

@keyframes scale-in-center {
    0% {
        -webkit-transform: scale(0);
        transform: scale(0);
        opacity: 1;
    }

    100% {
        -webkit-transform: scale(1);
        transform: scale(1);
        opacity: 1;
    }
}

.scale-out-center {
    -webkit-animation: scale-out-center 0.5s cubic-bezier(0.550, 0.085, 0.680, 0.530) both;
    animation: scale-out-center 0.5s cubic-bezier(0.550, 0.085, 0.680, 0.530) both;
}

/* ----------------------------------------------
 * Generated by Animista on 2024-8-20 23:34:10
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation scale-out-center
 * ----------------------------------------
 */
@-webkit-keyframes scale-out-center {
    0% {
        -webkit-transform: scale(1);
        transform: scale(1);
        opacity: 1;
    }

    100% {
        -webkit-transform: scale(0);
        transform: scale(0);
        opacity: 1;
    }
}

@keyframes scale-out-center {
    0% {
        -webkit-transform: scale(1);
        transform: scale(1);
        opacity: 1;
    }

    100% {
        -webkit-transform: scale(0);
        transform: scale(0);
        opacity: 1;
    }
}
</style>