<template>
    <div class="modal">
        <div class="modal-content" :class="styleClass">
            <span class="close" @click="close()">&times;</span>
            <h2>{{ title }}</h2>
            <div class="content-activity" v-if="(!openEditModal)">
                <h2>{{ titleActivity }}</h2>
                <p>{{ contentActivity }}</p>
            </div>
            <div class="content-options" v-if="(!openEditModal)">
                <Edit @click="openEditModal = true" />
                <Delete @click="deleteActivity()" />
            </div>
            <ModalEdit :activity="activity" :boardSectionId="boardSectionId" v-if="openEditModal"
                @closeEdit="openEditModal = false" />
        </div>
    </div>
</template>
<script setup>
import { defineEmits, defineProps, ref, watch } from 'vue'
import Activity from '../../models/Activity.js'
import Edit from '../icons/Edit.vue'
import Delete from '../icons/Delete.vue'
import ModalEdit from './ModalEdit.vue'
import store from '../../store/store.js'
import Board from '../../models/Board.js'

const props = defineProps({
    title: String,
    activity: {
        type: Activity,
        required: true
    },
    boardSectionId: String
})

let openEditModal = ref(false)

let title = ref(props.title)

let titleActivity = ref(props.activity.title)

let contentActivity = ref(props.activity.content)

let styleClass = ref('slide-in-top')

const emit = defineEmits(['close'])

function close() {
    styleClass.value = 'slide-out-top'
    setTimeout(()=> {
        openEditModal = false
        emit('close')
    }, 500)
}

function deleteActivity() {
    const indexSection = store.board.sections.findIndex(section => section.id == props.boardSectionId)

    store.board.sections[props.boardSectionId] = store.activityFunctions.removeActivity(store.board.sections[indexSection], props.activity)

    const boards = JSON.parse(localStorage.getItem('boards'))
    const board = Board.fromJSON(boards.find(board => board.id == store.board.id))

    board.sections[indexSection] = store.activityFunctions.removeActivity(board.sections[indexSection], props.activity)

    // replace element in boards who has the same id at the board
    const indexBoard = boards.findIndex(board => board.id == store.board.id)
    boards[indexBoard] = board

    localStorage.setItem('boards', JSON.stringify(boards))
    close()
}

watch(() => props.activity, (newValue, oldValue) => {
    titleActivity = newValue.title
    contentActivity = newValue.content
})

</script>
<style scoped>
.modal {
    position: fixed;
    z-index: 1000;
    left: 0;
    top: 0;
    width: 100%;
    height: 100%;
    background-color: rgba(0, 0, 0, 0.5);
}

.modal-content {
    background: #1a1822;
    ;
    margin: 15% auto;
    padding: 20px;
    border: 1px solid #888;
    border-radius: 5px;
    max-width: 400px;
}

.close {
    color: #aaa;
    float: right;
    font-size: 28px;
    font-weight: bold;
    cursor: pointer;
}

.close:hover,
.close:focus {
    color: black;
    text-decoration: none;
    cursor: pointer;
}

.content-activity {
    margin-bottom: 5px;
    padding: 5px;
}

.content-options {
    display: flex;
    justify-content: end;
    margin-bottom: 15px;
}

.slide-in-top {
    -webkit-animation: slide-in-top 0.5s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
    animation: slide-in-top 0.5s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
}

/* ----------------------------------------------
 * Generated by Animista on 2024-6-13 10:56:12
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-in-top
 * ----------------------------------------
 */
@-webkit-keyframes slide-in-top {
    0% {
        -webkit-transform: translateY(-1000px);
        transform: translateY(-1000px);
        opacity: 0;
    }

    100% {
        -webkit-transform: translateY(0);
        transform: translateY(0);
        opacity: 1;
    }
}

@keyframes slide-in-top {
    0% {
        -webkit-transform: translateY(-1000px);
        transform: translateY(-1000px);
        opacity: 0;
    }

    100% {
        -webkit-transform: translateY(0);
        transform: translateY(0);
        opacity: 1;
    }
}

.slide-out-top {
    -webkit-animation: slide-out-top 0.5s cubic-bezier(0.550, 0.085, 0.680, 0.530) both;
    animation: slide-out-top 0.5s cubic-bezier(0.550, 0.085, 0.680, 0.530) both;
}

/* ----------------------------------------------
 * Generated by Animista on 2024-6-13 10:59:16
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-out-top
 * ----------------------------------------
 */
@-webkit-keyframes slide-out-top {
    0% {
        -webkit-transform: translateY(0);
        transform: translateY(0);
        opacity: 1;
    }

    100% {
        -webkit-transform: translateY(-1000px);
        transform: translateY(-1000px);
        opacity: 0;
    }
}

@keyframes slide-out-top {
    0% {
        -webkit-transform: translateY(0);
        transform: translateY(0);
        opacity: 1;
    }

    100% {
        -webkit-transform: translateY(-1000px);
        transform: translateY(-1000px);
        opacity: 0;
    }
}
</style>